# This file was generated by GoReleaser. DO NOT EDIT.
class Gitlab < Formula
  desc "Create gitlab issue in project linked to current git repository using git editor and selecting optional template"
  homepage "https://github.com/stuart-warren/gitlab"
  version "0.0.1"
  license "BSD-3-clause"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stuart-warren/gitlab/releases/download/v0.0.1/gitlab_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "90d4e07f283f7d0df25a3b704c9b27f5a9d154b427d21c01352ce17859d65af2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stuart-warren/gitlab/releases/download/v0.0.1/gitlab_0.0.1_Linux_x86_64.tar.gz"
    sha256 "2b4eb2c3d4c97bbca490fc35c398da3761eee0e70599b66885d42327d06a2373"
  end

  depends_on "go"

  def install
    bin.install "gitlab"
  end

  test do
    system "#{bin}/gitlab -help"
  end
end
