# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localpod < Formula
  desc "A tool help local development environments"
  homepage "https://github.com/stuart-warren/localpod"
  version "0.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stuart-warren/localpod/releases/download/v0.0.1/localpod_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "851b43a63fcc940294a1319988abc8c262ec45dec675043fb204dc13ae14878f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stuart-warren/localpod/releases/download/v0.0.1/localpod_0.0.1_Linux_x86_64.tar.gz"
    sha256 "5ec42112f84be8edfd8f24e3b9cfda61c7a8178b3ee59bbc17cd8e475080a051"
  end

  depends_on "go"

  def install
    bin.install "localpod"
  end

  test do
    system "#{bin}/localpod -help"
  end
end
