# This file was generated by GoReleaser. DO NOT EDIT.
class Pair < Formula
  desc "A tool for pair programming"
  homepage "https://github.com/stuart-warren/pair"
  version "0.0.11"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stuart-warren/pair/releases/download/v0.0.11/pair_0.0.11_Darwin_x86_64.tar.gz"
    sha256 "4a2512a63c7484321d80f05ae0c67fdcf83f47f95a7bcb24d73996b039d014ff"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stuart-warren/pair/releases/download/v0.0.11/pair_0.0.11_Linux_x86_64.tar.gz"
    sha256 "8720912ffb406cf25eb827794681fbb79bdb154bf520f12caffa33e6c896bd84"
  end

  depends_on "go"

  def install
    bin.install "pair"
    bin.install "pair-server"
    bin.install "pair-server-simple"
  end

  test do
    system "#{bin}/pair -version"
  end
end
