# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbcopy < Formula
  desc "pbcopy for linux that works in the terminal over ssh"
  homepage "https://github.com/stuart-warren/remote-pbcopy"
  version "0.0.7"
  license "MIT"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stuart-warren/remote-pbcopy/releases/download/v0.0.7/remote-pbcopy_0.0.7_Linux_x86_64.tar.gz"
    sha256 "41152f7e2bcfa553744ed338d24fec0bfdc53006553066c88cc4c8fc4d8c9e79"
  end

  depends_on "go"

  def install
    bin.install "pbcopy"
  end

  test do
    system "#{bin}/pbcopy -h"
  end
end
