# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yamlfmt < Formula
  desc "based on gofmt, yamlfmt formats yaml files into a canonical format"
  homepage "https://github.com/stuart-warren/yamlfmt"
  version "0.2.0"
  license "BSD-3-clause"

  depends_on "go"

  on_macos do
    url "https://github.com/stuart-warren/yamlfmt/releases/download/v0.2.0/yamlfmt_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "ed5e1b437737df23d9496d05e5394861a3a1b25e34e49a029aff44d344fdcb9e"

    def install
      bin.install "yamlfmt"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Yamlfmt
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stuart-warren/yamlfmt/releases/download/v0.2.0/yamlfmt_0.2.0_Linux_x86_64.tar.gz"
      sha256 "c12631ba64fb734f8ce36c33efcd021020a5ecdf2f91bfba51f977bd5f1672c0"

      def install
        bin.install "yamlfmt"
      end
    end
  end

  test do
    system "#{bin}/yamlfmt -help"
  end
end
